esphome:
  name: uart-bridge
  includes:
    - uart_bridge.h
  on_boot:
    priority: 800
    then:
      - lambda: 'start_uart_bridge();'

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

logger:
  baud_rate: 0
  level: NONE
